In [6]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])                 #np.array uses homogenous data type to do calculations
print(a + b)
print(b - a)
print(a*b)

[5 7 9]
[3 3 3]
[ 4 10 18]


In [7]:
import numpy as np
a = np.array([1, "Hello"])              #If we send string all the things become string same with float as well
print(a)

['1' 'Hello']


In [1]:
import numpy as np
a = np.array([7])                       #It multiplies with each element if a single element is present in 1 array
b = np.array([4, 5, 6])
print(a*b)

[28 35 42]


In [10]:
import numpy as np
a = np.array([[2,4],[3,5,7]])            #Array should contain same dimension elements otherwise error
print(a)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [11]:
import numpy as np
a = np.array([3,5,7])
print(type(a))                          #Determine type of array

<class 'numpy.ndarray'>


In [17]:
import numpy as np
a = np.array([9,6,7,1,5,1,3])
print(a[0:4]) 
print(a[:-2])                           #Slicing in 1D Arrays
print(a[::-1]) 

[9 6 7 1]
[9 6 7 1 5]
[3 1 5 1 7 6 9]


In [18]:
import numpy as np
a = np.array([[9,6,7,1],[2,4,6,8]])
print(a[0:4]) 
 

TypeError: Field elements must be 2- or 3-tuples, got '2'